// Hand-built levels, drawn as ASCII maps. Every row must be the same width.
//
//   .  lawn (must all be mowed to finish)
//   #  house / garage roof   (solid: the mower bumps off it)
//   =  driveway or patio     (drive over it freely, nothing to cut)
//   *  flower bed            (drive over it and you trample the flowers)
//   T  tree trunk            (solid, with a canopy drawn over the lawn)
//   E  evergreen             (solid)
//   o  sprinkler head        (solid, small)
//   r  landscape rock        (solid)
//   ~  pool or pond          (solid)

export type Target = "any" | "vstripes" | "hstripes" | "checker" | "diamond";

export type Level = {
  id: string;
  name: string;
  hint: string;
  neighborhood: "Starter Yard" | "Suburban" | "Estate";
  target: Target;
  /** Seconds to beat for the time star. */
  par: number;
  dogs?: number;
  map: string[];
};

const W = ".".repeat(24);

export const levels: Level[] = [
  {
    id: "first-cut",
    name: "First Cut",
    neighborhood: "Starter Yard",
    hint: "Drag across the lawn to mow it. Every blade has to come down.",
    target: "any",
    par: 16,
    map: Array(14).fill(W),
  },
  {
    id: "classic-stripes",
    name: "Classic Stripes",
    neighborhood: "Starter Yard",
    hint: "Mow up the light bands and down the dark ones. That is how real stripes are made.",
    target: "vstripes",
    par: 24,
    map: Array(14).fill(W),
  },
  {
    id: "mind-the-tulips",
    name: "Mind the Tulips",
    neighborhood: "Starter Yard",
    hint: "Mow around the flower bed. Trampled tulips cost you a star.",
    target: "any",
    par: 22,
    map: [
      W,
      W,
      W,
      W,
      "........*******.........",
      ".......*********........",
      ".......*********........",
      "........*******.........",
      W,
      W,
      W,
      W,
      W,
      W,
    ],
  },
  {
    id: "side-to-side",
    name: "Side to Side",
    neighborhood: "Starter Yard",
    hint: "Horizontal stripes: mow right on the light bands and left on the dark ones.",
    target: "hstripes",
    par: 26,
    map: [
      W,
      W,
      W,
      ".................T......",
      W,
      W,
      W,
      W,
      ".....T..................",
      W,
      W,
      W,
      W,
      W,
    ],
  },
  {
    id: "front-yard",
    name: "The Front Yard",
    neighborhood: "Suburban",
    hint: "A real front yard: house up top, driveway on the side. Classic stripes.",
    target: "vstripes",
    par: 26,
    map: [
      "##########********====..",
      "##########********====..",
      "##########........====..",
      "##########........====..",
      "..................====..",
      "..................====..",
      "........T.........====..",
      "..................====..",
      "..................====..",
      "..................====..",
      "..................====..",
      "..................====..",
      "..................====..",
      "..................====..",
    ],
  },
  {
    id: "sprinkler-season",
    name: "Sprinkler Season",
    neighborhood: "Suburban",
    hint: "Sprinkler heads are hiding in the grass. Bumping one costs a star.",
    target: "hstripes",
    par: 28,
    map: [
      W,
      ".....o..........o.......",
      W,
      W,
      W,
      "...........o............",
      W,
      W,
      "..o.................o...",
      W,
      W,
      "..........o.............",
      W,
      W,
    ],
  },
  {
    id: "good-boy",
    name: "Good Boy",
    neighborhood: "Suburban",
    hint: "The neighbor's dog wants to help. Steer around him.",
    target: "any",
    par: 24,
    dogs: 1,
    map: [
      "====....................",
      "====....................",
      "====....................",
      W,
      W,
      "..............E.........",
      W,
      W,
      W,
      W,
      "....r...................",
      W,
      W,
      W,
    ],
  },
  {
    id: "checkerboard",
    name: "Checkerboard",
    neighborhood: "Suburban",
    hint: "Alternate direction block by block. Tricky, but it looks incredible.",
    target: "checker",
    par: 40,
    map: Array(15).fill(W),
  },
  {
    id: "garden-party",
    name: "Garden Party",
    neighborhood: "Estate",
    hint: "Beds everywhere and a party at six. Stripes up and down, no trampling.",
    target: "vstripes",
    par: 34,
    map: [
      "***.................****",
      "***.................****",
      "........................",
      "........T...............",
      "........................",
      "...............*****....",
      "...............*****....",
      "........................",
      "...E....................",
      "........................",
      "........................",
      "**..................T...",
      "**......................",
      "**......................",
    ],
  },
  {
    id: "pool-party",
    name: "Pool Party",
    neighborhood: "Estate",
    hint: "Mow the ring of lawn around the pool without taking a swim.",
    target: "vstripes",
    par: 32,
    map: [
      W,
      W,
      "......============......",
      "......=~~~~~~~~~~=......",
      "......=~~~~~~~~~~=......",
      "......=~~~~~~~~~~=......",
      "......=~~~~~~~~~~=......",
      "......============......",
      W,
      "..r..................r..",
      W,
      W,
      W,
      W,
    ],
  },
  {
    id: "the-estate",
    name: "The Estate",
    neighborhood: "Estate",
    hint: "A big lawn, two dogs, and a checkerboard finish. Take your time.",
    target: "checker",
    par: 58,
    dogs: 2,
    map: [
      "############======..............",
      "############======..............",
      "############======.......T......",
      "******************..............",
      "................................",
      "................................",
      ".........E.............***......",
      "......................*****.....",
      "......................*****.....",
      "................................",
      "..T.............................",
      "................................",
      "................................",
      "..............r.................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "championship",
    name: "Championship Diamonds",
    neighborhood: "Estate",
    hint: "The ballpark finish. Match the diamonds for all three stars.",
    target: "diamond",
    par: 60,
    dogs: 1,
    map: [
      "********................********",
      "**............................**",
      "................................",
      "................................",
      "................................",
      "................................",
      "..............T.................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "*..............................*",
      "********................********",
    ],
  },
];

/** Clearing this level (or getting 3 stars anywhere) unlocks the promo. */
export const PROMO_LEVEL_INDEX = 2;
